services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    pcak\BixieApi\EventListener\BixieApiLoginFormListener:
        public: true
    pcak\BixieApi\EventListener\BixieApiLogoutFormListener:
        public: true
    pcak\BixieApi\EventListener\BixieApiPostBeitragFormListener:
        public: true
    pcak\BixieApi\EventListener\BixieApiUpdatePosteingangFormListener:
        public: true
    pcak\BixieApi\EventListener\BixieApiOpenTicketFormListener:
        public: true       
    pcak\BixieApi\Controller\FrontendModule\BixieModulController:
        tags:
            -
                name: contao.frontend_module
                category: miscellaneous

 
 

