services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    pcak\BixieApi\EventListener\BixieApiLoginFormListener:
        public: true
    pcak\BixieApi\Controller\FrontendModule\BixieLoginStatusModulController:
        tags:
            -
                name: contao.frontend_module
                category: miscellaneous
                template: mod_bixie_login_status_modul
    pcak\BixieApi\Controller\FrontendModule\BixieBavListModulController:
        tags:
            -
                name: contao.frontend_module
                category: miscellaneous
                template: mod_bixie_bav_list_modul
 

